### ISSUE TITLE
Need basic authentication

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#39]
See: http://flask.pocoo.org/snippets/category/authentication/

HTTP Basic auth "is probably good enough" (thanks, flask!)

**Comment by Tsintsir** [comment]
See https://github.com/gitsubmit/gitsubmit-backend/blob/user/Tsintsir/basic_http_auth/src/security.py. I'm not sure if this is sufficient or redundant since it essentially reuses the basic authentication functionality we already have. Should we be using a token of some sort for sessions? That's the only alternative I can think of.

**Comment by Tsintsir** [comment]
Correct me if I'm wrong: this issue's scope has widened to include the implementation of token storage/generation as of 10/2.

**Comment by sonph** [comment]
Yes I think that's correct plus the verification of tokens as well. See [anatomy of json web token](https://scotch.io/tutorials/the-anatomy-of-a-json-web-token) and [pyjwt library](https://github.com/jpadilla/pyjwt/)
